package com.diffdb.migration;

import com.diffdb.diff.DiffCategory;
import com.diffdb.diff.DiffNode;
import com.diffdb.diff.SchemaDiffResult;
import com.diffdb.model.ColumnSnapshot;
import com.diffdb.model.IndexSnapshot;
import com.diffdb.model.SchemaSnapshot;
import com.diffdb.model.TableSnapshot;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates migration SQL directly from the {@link DiffNode} tree.
 * Produces MySQL-compatible DDL with backtick-quoted identifiers
 * (safe for reserved words like {@code desc}, {@code key}, etc.).
 */
public class FastMigrationSqlGenerator implements MigrationSqlGenerator {

    @Override
    public String generate(SchemaDiffResult diff, MigrationOptions options) throws Exception {
        StringBuilder sql = new StringBuilder();
        sql.append("-- Migration generated by DiffDB\n");
        sql.append("-- Brings the target schema in line with the source.\n");
        if (options.isIncludeSchema() && options.getTargetSchema() != null) {
            sql.append("-- Target schema: ").append(options.getTargetSchema()).append("\n");
        }
        sql.append("\n");

        List<String> drops = new ArrayList<>();
        List<String> adds = new ArrayList<>();
        List<String> alters = new ArrayList<>();

        for (DiffNode root : diff.getRoots()) {
            collectStatements(root, diff, options, drops, adds, alters);
        }

        if (!options.isIncludeDrops()) {
            drops.clear();
        }

        if (drops.isEmpty() && adds.isEmpty() && alters.isEmpty()) {
            sql.append("-- (no changes)\n");
            return sql.toString();
        }

        for (String stmt : drops) sql.append(stmt).append(";\n");
        // ADD COLUMNs first (so CREATE INDEX has the columns available)
        for (String stmt : adds) {
            if (stmt.startsWith("ALTER TABLE")) {
                sql.append(stmt).append(";\n");
            }
        }
        // CREATE INDEXes after all columns are added
        for (String stmt : adds) {
            if (!stmt.startsWith("ALTER TABLE")) {
                sql.append(stmt).append(";\n");
            }
        }
        for (String stmt : alters) sql.append(stmt).append(";\n");

        return sql.toString();
    }

    private void collectStatements(DiffNode node, SchemaDiffResult diff, MigrationOptions options,
                                    List<String> drops, List<String> adds, List<String> alters) {
        if (node.getCategory() == DiffCategory.CONTAINER) {
            for (DiffNode child : node.getChildren()) {
                collectStatements(child, diff, options, drops, adds, alters);
            }
            return;
        }

        String type = node.getObjectType();
        String name = node.getName();
        DiffCategory category = node.getCategory();
        String detail = node.getDetail();

        switch (type) {
            case "Table":
                handleTable(name, category, diff, options, drops, adds);
                break;
            case "Column":
                handleColumn(name, category, detail, options, drops, adds, alters);
                break;
            case "Index":
                handleIndex(name, category, detail, options, drops, adds, alters);
                break;
            case "PrimaryKey":
                handlePrimaryKey(name, category, options, drops, adds, alters);
                break;
            case "ForeignKey":
                handleForeignKey(name, category, options, drops, adds, alters);
                break;
        }
    }

    // -- Table --

    private void handleTable(String name, DiffCategory category,
                             SchemaDiffResult diff, MigrationOptions options,
                             List<String> drops, List<String> adds) {
        if (category == DiffCategory.MISSING) {
            SchemaSnapshot source = diff.getSourceSnapshot();
            TableSnapshot table = source == null ? null : source.getTables().get(name);
            if (table != null) {
                adds.add(buildCreateTable(table, options));
            } else {
                adds.add("-- CREATE TABLE " + qualify(name, options) + " (not generated: use GUI or script)");
            }
        } else if (category == DiffCategory.UNEXPECTED) {
            drops.add("DROP TABLE IF EXISTS " + qualify(name, options));
        }
    }

    private String buildCreateTable(TableSnapshot table, MigrationOptions options) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLE ").append(qualify(table.getName(), options)).append(" (\n");

        List<String> columnDefs = new ArrayList<>();
        for (ColumnSnapshot col : table.getColumns().values()) {
            StringBuilder def = new StringBuilder();
            def.append("  ").append(bt(col.getName())).append(" ").append(col.getSqlType());
            if (!col.isNullable()) def.append(" NOT NULL");
            if (col.getDefaultValue() != null && !col.getDefaultValue().isBlank())
                def.append(" DEFAULT ").append(col.getDefaultValue());
            if (col.isAutoIncrement()) def.append(" AUTO_INCREMENT");
            if (col.getRemarks() != null && !col.getRemarks().isBlank())
                def.append(" COMMENT '").append(col.getRemarks().replace("'", "\\'")).append("'");
            columnDefs.add(def.toString());
        }

        if (!table.getPrimaryKeyColumns().isEmpty()) {
            String pkCols = table.getPrimaryKeyColumns().stream()
                    .map(FastMigrationSqlGenerator::bt).collect(Collectors.joining(", "));
            columnDefs.add("  PRIMARY KEY (" + pkCols + ")");
        }

        sb.append(String.join(",\n", columnDefs));
        sb.append("\n)");

        // Indexes
        List<String> pkCols = table.getPrimaryKeyColumns();
        List<String> indexStmts = new ArrayList<>();
        for (IndexSnapshot idx : table.getIndexes().values()) {
            if ("PRIMARY".equalsIgnoreCase(idx.getName())) continue;
            if (idx.isUnique() && idx.getColumns().equals(pkCols)) continue;
            String cols = idx.getColumns().stream()
                    .map(FastMigrationSqlGenerator::bt).collect(Collectors.joining(", "));
            String idxType = idx.isUnique() ? "CREATE UNIQUE INDEX " : "CREATE INDEX ";
            indexStmts.add(idxType + bt(idx.getName()) + " ON "
                    + qualify(table.getName(), options) + " (" + cols + ")");
        }

        if (!indexStmts.isEmpty()) {
            sb.append(";\n").append(String.join(";\n", indexStmts));
        }
        return sb.toString();
    }

    // -- Column --

    private void handleColumn(String name, DiffCategory category, String detail,
                              MigrationOptions options,
                              List<String> drops, List<String> adds, List<String> alters) {
        int dot = name.lastIndexOf('.');
        if (dot < 0) return;
        String table = name.substring(0, dot);
        String column = name.substring(dot + 1);

        if (category == DiffCategory.MISSING) {
            String type = "VARCHAR(255)";
            if (detail != null && detail.contains("type:")) {
                type = extractAfter(detail, "type:");
            }
            adds.add("ALTER TABLE " + qualify(table, options)
                    + " ADD COLUMN " + bt(column) + " " + type);
        } else if (category == DiffCategory.UNEXPECTED) {
            drops.add("ALTER TABLE " + qualify(table, options)
                    + " DROP COLUMN " + bt(column));
        } else if (category == DiffCategory.CHANGED) {
            String newType = extractAfter(detail, "sqltype:");
            if (newType == null || newType.isEmpty()) {
                newType = extractAfter(detail, "type:");
            }
            if (newType == null || newType.isEmpty()) {
                newType = "VARCHAR(255)";
            }

            StringBuilder alter = new StringBuilder();
            alter.append("ALTER TABLE ").append(qualify(table, options))
                 .append(" MODIFY COLUMN ").append(bt(column)).append(" ").append(newType);

            // Include nullable change (use SOURCE value = before "->")
            String nullableVal = extractSource(detail, "nullable:");
            if ("false".equalsIgnoreCase(nullableVal)) {
                alter.append(" NOT NULL");
            } else if ("true".equalsIgnoreCase(nullableVal)) {
                alter.append(" NULL");
            }

            // Include default value change (use SOURCE value = before "->")
            String defVal = extractSource(detail, "defaultValue:");
            if (defVal != null && !defVal.isEmpty()) {
                String trimmed = defVal.trim();
                if ("null".equalsIgnoreCase(trimmed)) {
                    alter.append(" DEFAULT NULL");
                } else {
                    alter.append(" DEFAULT ").append(trimmed);
                }
            }

            alters.add(alter.toString());
        }
    }

    // -- Index --

    private void handleIndex(String name, DiffCategory category, String detail,
                             MigrationOptions options,
                             List<String> drops, List<String> adds, List<String> alters) {
        int dot = name.lastIndexOf('.');
        if (dot < 0) return;
        String table = name.substring(0, dot);
        String index = name.substring(dot + 1);

        if (category == DiffCategory.MISSING) {
            String cols = extractAfter(detail, "columns:");
            if (cols == null || cols.isEmpty()) {
                cols = "columns";
            }
            String quotedCols = Arrays.stream(cols.split(","))
                    .map(String::trim)
                    .map(n -> n.startsWith("`") ? n : bt(n))
                    .collect(Collectors.joining(", "));
            adds.add("CREATE INDEX " + bt(index) + " ON "
                    + qualify(table, options) + " (" + quotedCols + ")");
        } else if (category == DiffCategory.UNEXPECTED) {
            // MySQL: ALTER TABLE t DROP INDEX idx (universal, all versions)
            drops.add("ALTER TABLE " + qualify(table, options)
                    + " DROP INDEX " + bt(index));
        }
    }

    // -- PrimaryKey / ForeignKey --

    private void handlePrimaryKey(String name, DiffCategory category,
                                  MigrationOptions options,
                                  List<String> drops, List<String> adds, List<String> alters) {
        if (category == DiffCategory.MISSING) {
            adds.add("-- ADD PRIMARY KEY to " + qualify(name, options));
        } else if (category == DiffCategory.UNEXPECTED) {
            drops.add("ALTER TABLE " + qualify(name, options) + " DROP PRIMARY KEY");
        } else if (category == DiffCategory.CHANGED) {
            alters.add("-- MODIFY PRIMARY KEY on " + qualify(name, options));
        }
    }

    private void handleForeignKey(String name, DiffCategory category,
                                  MigrationOptions options,
                                  List<String> drops, List<String> adds, List<String> alters) {
        int dot = name.lastIndexOf('.');
        if (dot < 0) return;
        String table = name.substring(0, dot);
        String fk = name.substring(dot + 1);

        if (category == DiffCategory.MISSING) {
            adds.add("-- ADD FOREIGN KEY " + bt(fk) + " to " + qualify(table, options));
        } else if (category == DiffCategory.UNEXPECTED) {
            drops.add("ALTER TABLE " + qualify(table, options)
                    + " DROP FOREIGN KEY " + bt(fk));
        }
    }

    // -- Helpers --

    private static String qualify(String name, MigrationOptions options) {
        if (options.isIncludeSchema() && options.getTargetSchema() != null
                && !options.getTargetSchema().isBlank()) {
            return bt(options.getTargetSchema()) + "." + bt(name);
        }
        return bt(name);
    }

    /** Backtick-quote a MySQL identifier (safe for reserved words). */
    private static String bt(String identifier) {
        if (identifier == null) return "``";
        return "`" + identifier.replace("`", "``") + "`";
    }

    private static String extractAfter(String detail, String prefix) {
        if (detail == null) return null;
        int idx = detail.indexOf(prefix);
        if (idx < 0) return null;
        int start = idx + prefix.length();
        while (start < detail.length() && detail.charAt(start) == ' ') start++;
        int end = detail.indexOf(';', start);
        if (end < 0) end = detail.length();
        String value = detail.substring(start, end).trim();
        int arrow = value.indexOf(" -> ");
        if (arrow > 0) {
            return value.substring(arrow + 4).trim();  // target value
        }
        return value;
    }

    /** Like extractAfter but returns the SOURCE value (before "->") when present. */
    private static String extractSource(String detail, String prefix) {
        if (detail == null) return null;
        int idx = detail.indexOf(prefix);
        if (idx < 0) return null;
        int start = idx + prefix.length();
        while (start < detail.length() && detail.charAt(start) == ' ') start++;
        int end = detail.indexOf(';', start);
        if (end < 0) end = detail.length();
        String value = detail.substring(start, end).trim();
        int arrow = value.indexOf(" -> ");
        if (arrow > 0) {
            return value.substring(0, arrow).trim();  // source value
        }
        return value;
    }
}
