package com.diffdb.migration;

import com.diffdb.diff.SchemaDiffResult;
import liquibase.Scope;
import liquibase.change.Change;
import liquibase.changelog.ChangeSet;
import liquibase.database.Database;
import liquibase.diff.DiffResult;
import liquibase.diff.output.DiffOutputControl;
import liquibase.diff.output.changelog.DiffToChangeLog;
import liquibase.resource.ClassLoaderResourceAccessor;
import liquibase.sql.Sql;
import liquibase.sqlgenerator.SqlGeneratorFactory;
import liquibase.statement.SqlStatement;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * {@link MigrationSqlGenerator} backed by Liquibase. Converts the diff into change
 * sets and renders each change as SQL in the <b>target database dialect</b>.
 */
public class LiquibaseMigrationSqlGenerator implements MigrationSqlGenerator {

    @Override
    public String generate(SchemaDiffResult diff, MigrationOptions options) throws Exception {
        DiffResult diffResult = diff.getRawDiff();
        if (diffResult == null) {
            return "-- No diff result available.";
        }

        Map<String, Object> scopeValues = new HashMap<>();
        scopeValues.put(Scope.Attr.resourceAccessor.name(), new ClassLoaderResourceAccessor());

        return Scope.child(scopeValues, () -> render(diffResult, options));
    }

    private String render(DiffResult diffResult, MigrationOptions options) throws Exception {
        Database targetDb = diffResult.getComparisonSnapshot().getDatabase();

        DiffOutputControl outputControl = new DiffOutputControl(
                false,                       // includeCatalog
                options.isIncludeSchema(),   // includeSchema
                false,                       // includeTablespace
                null);                       // schemaComparisons

        DiffToChangeLog diffToChangeLog = new DiffToChangeLog(diffResult, outputControl);
        List<ChangeSet> changeSets = diffToChangeLog.generateChangeSets();

        StringBuilder sql = new StringBuilder();
        sql.append("-- Migration generated by DiffDB\n");
        sql.append("-- Brings the target schema in line with the source.\n\n");

        for (ChangeSet changeSet : changeSets) {
            for (Change change : changeSet.getChanges()) {
                if (!options.isIncludeDrops() && isDrop(change)) {
                    continue;
                }
                appendChangeSql(sql, change, targetDb);
            }
        }

        if (sql.indexOf(";") < 0) {
            sql.append("-- (no statements)\n");
        }
        return sql.toString();
    }

    private void appendChangeSql(StringBuilder sql, Change change, Database targetDb) {
        SqlStatement[] statements = change.generateStatements(targetDb);
        for (SqlStatement statement : statements) {
            Sql[] generated = SqlGeneratorFactory.getInstance().generateSql(statement, targetDb);
            for (Sql s : generated) {
                sql.append(s.toSql());
                String delimiter = s.getEndDelimiter();
                sql.append(delimiter == null ? ";" : delimiter);
                sql.append('\n');
            }
        }
    }

    private boolean isDrop(Change change) {
        return change.getClass().getSimpleName().startsWith("Drop");
    }
}
