package com.diffdb.migration;

import com.diffdb.diff.LiquibaseScope;
import com.diffdb.diff.SchemaDiffResult;
import com.intellij.openapi.diagnostic.Logger;
import liquibase.change.Change;
import liquibase.changelog.ChangeSet;
import liquibase.database.Database;
import liquibase.diff.DiffResult;
import liquibase.diff.output.DiffOutputControl;
import liquibase.diff.output.changelog.DiffToChangeLog;
import liquibase.snapshot.DatabaseSnapshot;
import liquibase.sql.Sql;
import liquibase.sqlgenerator.SqlGeneratorFactory;
import liquibase.statement.SqlStatement;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class LiquibaseMigrationSqlGenerator implements MigrationSqlGenerator {

    private static final Logger LOG = Logger.getInstance(LiquibaseMigrationSqlGenerator.class);

    @Override
    public String generate(SchemaDiffResult diff, MigrationOptions options) throws Exception {
        DiffResult diffResult = diff.getRawDiff();
        if (diffResult == null) {
            return "-- No diff result available.";
        }

        return LiquibaseScope.run(() -> render(diffResult, options));
    }

    private String render(DiffResult diffResult, MigrationOptions options) throws Exception {
        DatabaseSnapshot comparisonSnapshot = diffResult.getComparisonSnapshot();
        if (comparisonSnapshot == null) {
            return "-- Error: comparison snapshot is null; the diff may not have been computed correctly.";
        }

        Database targetDb = comparisonSnapshot.getDatabase();
        if (targetDb == null) {
            return "-- Error: target database is null; the diff may not have been computed correctly.";
        }

        DiffOutputControl outputControl = new DiffOutputControl(
                false,
                options.isIncludeSchema(),
                false,
                null);

        DiffToChangeLog diffToChangeLog = new DiffToChangeLog(diffResult, outputControl);

        StringBuilder sql = new StringBuilder();
        sql.append("-- Migration generated by DiffDB\n");
        sql.append("-- Brings the target schema in line with the source.\n\n");

        try {
            List<ChangeSet> changeSets = diffToChangeLog.generateChangeSets();

            if (changeSets == null || changeSets.isEmpty()) {
                sql.append("-- (no changes)\n");
                return sql.toString();
            }

            for (ChangeSet changeSet : changeSets) {
                List<Change> changes = changeSet.getChanges();
                if (changes == null) {
                    continue;
                }
                for (Change change : changes) {
                    if (change == null) {
                        continue;
                    }
                    if (!options.isIncludeDrops() && isDrop(change)) {
                        continue;
                    }
                    try {
                        appendChangeSql(sql, change, targetDb);
                    } catch (Exception e) {
                        LOG.warn("Failed to generate SQL for change: " + change.getClass().getSimpleName(), e);
                        sql.append("-- ERROR generating SQL for: ")
                                .append(change.getClass().getSimpleName())
                                .append("\n-- ").append(e.getMessage()).append("\n\n");
                    }
                }
            }
        } catch (Exception e) {
            LOG.error("generateChangeSets failed", e);
            return "-- Error generating change sets: " + e.getMessage();
        }

        String raw = sql.toString();
        if (raw.indexOf(';') < 0 && !raw.contains("(no changes)") && !raw.contains("ERROR")) {
            sql.append("-- (no statements)\n");
        }
        return mergeAlterTableStatements(sql.toString());
    }

    private void appendChangeSql(StringBuilder sql, Change change, Database targetDb) {
        SqlStatement[] statements = change.generateStatements(targetDb);
        if (statements == null) {
            return;
        }
        for (SqlStatement statement : statements) {
            if (statement == null) {
                continue;
            }
            try {
                Sql[] generated = SqlGeneratorFactory.getInstance().generateSql(statement, targetDb);
                if (generated == null) {
                    continue;
                }
                for (Sql s : generated) {
                    if (s == null) {
                        continue;
                    }
                    sql.append(s.toSql());
                    String delimiter = s.getEndDelimiter();
                    sql.append(delimiter == null ? ";" : delimiter);
                    sql.append('\n');
                }
            } catch (NullPointerException e) {
                // Known Liquibase bug: some statements contain null objects internally
                LOG.warn("Skipping statement with null value: " + statement.getClass().getSimpleName(), e);
            } catch (Exception e) {
                LOG.warn("Failed to generate SQL for statement: " + statement.getClass().getSimpleName(), e);
                sql.append("-- ERROR generating SQL for: ")
                        .append(statement.getClass().getSimpleName())
                        .append("\n-- ").append(e.getMessage()).append("\n\n");
            }
        }
    }

    /**
     * Merges consecutive ALTER TABLE ... MODIFY statements for the same table+column
     * into a single statement, keeping the most complete definition.
     */
    private static String mergeAlterTableStatements(String rawSql) {
        String[] lines = rawSql.split("\n");
        List<String> result = new ArrayList<>();
        // key: "tableName.columnName" -> SQL line (most recent / complete)
        Map<String, String> alterMap = new LinkedHashMap<>();

        Pattern pattern = Pattern.compile(
                "ALTER\\s+TABLE\\s+(\\S+)\\s+MODIFY\\s+(\\S+)",
                Pattern.CASE_INSENSITIVE);

        for (String line : lines) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("--")) {
                result.add(line);
                continue;
            }
            Matcher m = pattern.matcher(trimmed);
            if (m.find()) {
                String table = m.group(1);
                String column = m.group(2);
                String key = table + "." + column;
                alterMap.put(key, line);
            } else {
                // Flush any pending ALTER statements before adding non-ALTER line
                if (!alterMap.isEmpty()) {
                    result.addAll(alterMap.values());
                    alterMap.clear();
                }
                result.add(line);
            }
        }
        // Flush remaining ALTER statements
        result.addAll(alterMap.values());

        return String.join("\n", result);
    }

    private boolean isDrop(Change change) {
        return change.getClass().getSimpleName().startsWith("Drop");
    }
}
